<template>
  <q-page>
    <div class="q-pa-md row justify-center">

      <!-- view all units -->
      <q-card flat bordered class="col-md-7 col-12 q-ma-sm full-height">
        <q-expansion-item
          v-for="(units, floorIndex) in allUnits"
          :key="floorIndex"
          :label="`${floorLabels[floorIndex]} (${units.length} items)`"
          expand-separator
          v-model="expanded[floorIndex]"
          @show="handleExpansion(floorIndex)"
        >
          <q-list class="row justify-center">
            <q-card
              v-for="unit in units"
              :key="unit._id"
              flat bordered
              class="q-ma-sm"
            >
              <q-card-section class="column flex-center">
                <div class="text-h6">

                  <!-- unit number -->
                  Unit {{ unit.unitNumber }}

                  <!-- available status -->
                  (<span v-if="unit.unitStatus === 'Available'" :class="{ 'available-unit': unit.unitStatus === 'Available'}">
                    {{ unit.unitStatus }}
                  </span>
                  <span v-else :class="{ 'occupied-unit': unit.unitStatus === 'Occupied'}">
                    {{ unit.unitStatus }}
                  </span>)
                </div>
                <!-- shared + bed count -->
                <div class="text-caption">{{ unit.unitType }} - {{ unit.unitOccupants - unit.currentOccupants }}/{{ unit.unitOccupants }} Beds</div>

              </q-card-section>
              <q-card-section class="row justify-center">
                <q-img
                  v-if="unit.images && unit.images.length > 0"
                  :src="getImageUrl(unit.images[0].imageUrl)"
                  class="image"
                />
              </q-card-section>
              <q-card-section class="row justify-between">
                <CustomButton label="Update " customStyle="width: 40%" color="white" text-color="black" @click="openUnitDetails(unit)" />
                <CustomButton label="Delete " customStyle="width: 40%" @click="deleteUnit(unit)" />
              </q-card-section>
            </q-card>
          </q-list>
        </q-expansion-item>
      </q-card>

      <!-- add new unit -->
      <q-card flat class="col-md-3 col-12 q-ma-sm full-height">
        <q-card-section>
          <div class="text-h6">Add a new unit</div>
        </q-card-section>
        <!-- <q-separator /> -->
        <q-card-section>
          <div class="q-mb-sm">When adding new units to the system, please note the following guidelines:</div>
          <ul>
            <li class="q-mb-sm">Units will be assigned the next available unit number based on the highest existing unit number for the selected floor level.</li>
            <li class="q-mb-sm">Each unit entry can accommodate a maximum of three images which must be provided during the creation process.</li>
            <li class="q-mb-sm">Unit numbers are automatically generated by the system and cannot be manually altered to ensure <span style="text-decoration: underline;">consistency and accuracy.</span></li>
          </ul>
        </q-card-section>
        <q-card-section>
          <CustomButton color="black" text-color="white" label="Add New" @click="openAddUnitsDialog" />
        </q-card-section>
      </q-card>
    </div>
    <q-dialog v-model="updateDetailsDialog">
      <AdminUnitDetailsComponent :unit="selectedUnit" @close="handleClose" />
    </q-dialog>
    <q-dialog v-model="addUnitsDialog">
      <AdminAddUnitComponent @close="handleClose" />
    </q-dialog>
  </q-page>
</template>

<script>
import UnitService from 'src/services/UnitService';
import CustomButton from 'src/components/elements/CustomButton.vue';
import Helper from 'src/services/utils';
import AdminAddUnitComponent from 'src/components/admin/AdminAddUnitComponent.vue';
import AdminUnitDetailsComponent from 'src/components/admin/AdminUnitDetailsComponent.vue';

export default {
  name: "AdminUnitsCard",

  data() {
    return {
      units: [],
      allUnits: [],
      // floorLabels: ['Ground Floor', 'First Floor', 'Second Floor'],
      floorLabels: ['First Floor', 'Second Floor', 'Third Floor'],

      addUnitsDialog: false,

      selectedUnit: null,
      updateDetailsDialog: false,

      expanded: [true, false, false]
    };
  },
  components: {
    CustomButton,
    AdminAddUnitComponent,
    AdminUnitDetailsComponent
  },
  methods: {
    getImageUrl: Helper.getImageUrl,
    capitalizeFirstLetter: Helper.capitalizeFirstLetter,

    async findAllUnits() {
      const response = await UnitService.getAllUnits();
      this.units = response;

      const sortedUnits = Helper.sortByProperty(this.units, 'unitNumber', 'asc')

      // const groundFloorUnits = sortedUnits.filter(unit => unit.floorLevel === 'Ground Floor')
      // const firstFloorUnits = sortedUnits.filter(unit => unit.floorLevel === 'First Floor')
      // const secondFloorUnits = sortedUnits.filter(unit => unit.floorLevel === 'Second Floor')

      const groundFloorUnits = sortedUnits.filter(unit => unit.floorLevel === 'First Floor')
      const firstFloorUnits = sortedUnits.filter(unit => unit.floorLevel === 'Second Floor')
      const secondFloorUnits = sortedUnits.filter(unit => unit.floorLevel === 'Third Floor')

      this.allUnits = [groundFloorUnits, firstFloorUnits, secondFloorUnits];
    },

    async deleteUnit(unit) {
      // Check if there are active or pending rentals
      const hasActiveRentals = unit.rentedHistory.some(rental => rental.status !== 'Ended');

      if (hasActiveRentals) {
        this.$q.notify({
          type: 'negative',
          message: 'This unit cannot be deleted as it still has active or pending rentals.'
        });
        return;
      }

      // Proceed with deletion confirmation
      this.$q.dialog({
        title: 'Confirm',
        message: `You are about to delete this unit entry. This action is irreversible. However, it will not remove the entry from the associated rental application, which must be manually deleted. Proceed with caution. Do you wish to continue?`,
        color: 'primary',
        cancel: true,
        persistent: true
      }).onOk(async () => {
        const response = await UnitService.deleteUnit(unit._id);
        if (response) {
          this.$q.notify({ type: 'positive', color: 'primary', message: 'Unit Deleted!' });
          this.findAllUnits();
        } else {
          this.$q.notify({ type: 'negative', message: 'Failed to delete unit. Please try again.' });
        }
      }).onCancel(() => {
        return;
      });
    },
    openAddUnitsDialog() {
      this.addUnitsDialog = true;
    },
    openUnitDetails(unit) {
      this.selectedUnit = unit,
      this.updateDetailsDialog = true
    },

    handleClose() {
      this.updateDetailsDialog = false
      this.addUnitsDialog = false;
      this.findAllUnits();
    },
    handleExpansion(expandedIndex) {
      this.expanded = this.expanded.map((_, index) => index === expandedIndex)
    }
  },
  created() {
    this.findAllUnits();
  },
};
</script>
